#ifndef __JAKARTA_AST_H__
#define __JAKARTA_AST_H__

#include "token.h"
#include "array.h"

typedef enum ASTIdentifierDef {
    AST_IDENTIFIER_BASE_PROGRAM,

    AST_IDENTIFIER_TYPE_DEFINITION,
    AST_IDENTIFIER_TYPE_DEFINITION_ALIAS,
    AST_IDENTIFIER_TYPE_DEFINITION_TYPE,

    AST_IDENTIFIER_FUNCTION_DEFINITION,
    AST_IDENTIFIER_FUNCTION_RETURN_TYPE,
    AST_IDENTIFIER_FUNCTION_PARAMETERS,
    AST_IDENTIFIER_FUNCTION_PARAMETER,
    AST_IDENTIFIER_FUNCTION_PARAMETER_TYPE,
    AST_IDENTIFIER_FUNCTION_BODY,
    AST_IDENTIFIER_FUNCTION_CALL,

    AST_IDENTIFIER_VARIABLE_DEFINITION,
    AST_IDENTIFIER_VARIABLE_TYPE,
    AST_IDENTIFIER_VARIABLE_CONTENT,

    AST_IDENTIFIER_CLASS_CREATOR,
    AST_IDENTIFIER_CLASS_BODY,

    AST_IDENTIFIER_IF_STATEMENT,
    AST_IDENTIFIER_IF_CONDITION,
    AST_IDENTIFIER_IF_BODY,
    AST_IDENTIFIER_ELSE_BODY,
    AST_IDENTIFIER_ELSE_IF_LIST,
    AST_IDENTIFIER_ELSE_IF_STATEMENT,
    AST_IDENTIFIER_ELSE_IF_BODY,

    AST_IDENTIFIER_INCREMENT,
    AST_IDENTIFIER_DECREMENT,

    AST_IDENTIFIER_OPERATOR,
    AST_IDENTIFIER_VALUE,
    
    AST_IDENTIFIER_RETURN,

    AST_IDENTIFIER_FOR,
    AST_IDENTIFIER_FOR_INITIALIZATION,
    AST_IDENTIFIER_FOR_CONDITION,
    AST_IDENTIFIER_FOR_ITERATION,
    AST_IDENTIFIER_FOR_BODY,

    AST_IDENTIFIER_ARRAY_ACCESS,
    AST_IDENTIFIER_INDEX
} ASTIdentifier;

typedef struct ASTNodeDef {
    ASTIdentifier identifier;
    Token* token;
    Array* nodes;
} ASTNode;

typedef struct ASTDef {
    ASTNode* root;
} AST;

ASTNode* create_ast_node(ASTIdentifier identifier, Token* token);
AST* create_ast();
void print_ast_node(ASTNode* node, int depth);

unsigned int precedence(char* operator);

#endif