#ifndef __JAKARTA_AST_H__
#define __JAKARTA_AST_H__

#include "token.h"

typedef enum ASTIdentifierDef {
    AST_IDENTIFIER_BASE_PROGRAM,

    AST_IDENTIFIER_TYPE_DEFINITION,
    AST_IDENTIFIER_TYPE_DEFINITION_ALIAS,
    AST_IDENTIFIER_TYPE_DEFINITION_TYPE,

    AST_IDENTIFIER_FUNCTION_DEFINITION,
    AST_IDENTIFIER_FUNCTION_RETURN_TYPE,
    AST_IDENTIFIER_FUNCTION_PARAMETERS,
    AST_IDENTIFIER_FUNCTION_BODY,

    AST_IDENTIFIER_VARIABLE_DEFINITION,
    AST_IDENTIFIER_VARIABLE_TYPE,
    AST_IDENTIFIER_VARIABLE_CONTENT,

    AST_IDENTIFIER_CLASS_CREATOR,

    AST_IDENTIFIER_IF_STATEMENT,
    AST_IDENTIFIER_IF_CONDITION,
    AST_IDENTIFIER_IF_BODY,
    AST_IDENTIFIER_ELSE_BODY,
    AST_IDENTIFIER_ELSE_IF_LIST,
    AST_IDENTIFIER_ELSE_IF_STATEMENT,
    AST_IDENTIFIER_ELSE_IF_BODY,

    AST_IDENTIFIER_INCREMENT,
    AST_IDENTIFIER_DECREMENT
} ASTIdentifier;

typedef struct ASTNodeDef {
    ASTIdentifier identifier;
    Token* token;
    struct ASTNodeDef** nodes;
    unsigned short nodes_length;
    unsigned short nodes_capacity;
} ASTNode;

typedef struct ASTDef {
    ASTNode* root;
} AST;

ASTNode* createASTNode(ASTIdentifier identifier, Token* token);
AST* createAST();
void addASTNode(ASTNode* parent, ASTNode* child);
void printASTNode(ASTNode* node, int depth);

#endif