#ifndef __JAKARTA_AST_H__
#define __JAKARTA_AST_H__

typedef enum ASTIdentifierDef {
    AST_IDENTIFIER_TYPE_DEFINITION,
    AST_IDENTIFIER_TYPE_DEFINITION_ALIAS,
    AST_IDENTIFIER_TYPE_DEFINITION_TYPE,

    AST_IDENTIFIER_FUNCTION_DEFINITION,
    AST_IDENTIFIER_FUNCTION_RETURN_TYPE,
    AST_IDENTIFIER_FUNCTION_PARAMETERS,
    AST_IDENTIFIER_FUNCTION_BODY,

    AST_IDENTIFIER_VARIABLE_DEFINITION,
    AST_IDENTIFIER_VARIABLE_TYPE,
    AST_IDENTIFIER_VARIABLE_CONTENT
} ASTIdentifier;

#endif