#ifndef __JAKARTA_SYMBOL_H__
#define __JAKARTA_SYMBOL_H__

#include <stdbool.h>

typedef enum SymbolDef {
    SYMBOL_STRING,
    SYMBOL_NUMBER,
    SYMBOL_BACKTICK,
    SYMBOL_TILDE,
    SYMBOL_EXCLAMATION,
    SYMBOL_AT,
    SYMBOL_HASHTAG,
    SYMBOL_DOLLAR,
    SYMBOL_PERCENT,
    SYMBOL_CARROT,
    SYMBOL_AMPERSAND,
    SYMBOL_ASTERISK,
    SYMBOL_OPEN_PARENTHESIS,
    SYMBOL_CLOSE_PARENTHESIS,
    SYMBOL_UNDERSCORE,
    SYMBOL_DASH,
    SYMBOL_PLUS,
    SYMBOL_EQUALS,
    SYMBOL_OPEN_BRACE,
    SYMBOL_CLOSE_BRACE,
    SYMBOL_OPEN_BRACKET,
    SYMBOL_CLOSE_BRACKET,
    SYMBOL_VERTICAL_LINE,
    SYMBOL_BACKSLASH,
    SYMBOL_COLON,
    SYMBOL_SEMICOLON,
    SYMBOL_QUOTATION,
    SYMBOL_APOSTRAPHE,
    SYMBOL_OPEN_ANGLE,
    SYMBOL_CLOSE_ANGLE,
    SYMBOL_COMMA,
    SYMBOL_PERIOD,
    SYMBOL_QUESTION,
    SYMBOL_SLASH,
    SYMBOL_NEWLINE,
    SYMBOL_SPACE,
    SYMBOL_NONE,

    KEYWORD_AS,
    KEYWORD_ASSERT,
    KEYWORD_BREAK,
    KEYWORD_CASE,
    KEYWORD_CATCH,
    KEYWORD_CLASS,
    KEYWORD_CONSTANT,
    KEYWORD_DO,
    KEYWORD_ELSE,
    KEYWORD_ENUM,
    KEYWORD_EXTENDS,
    KEYWORD_FINALLY,
    KEYWORD_FOR,
    KEYWORD_FROM,
    KEYWORD_FUNC,
    KEYWORD_GOTO,
    KEYWORD_IF,
    KEYWORD_INTERFACE,
    KEYWORD_IMPORT,
    KEYWORD_NEW,
    KEYWORD_PRIV,
    KEYWORD_PROT,
    KEYWORD_PUB,
    KEYWORD_RET,
    KEYWORD_STATIC,
    KEYWORD_SWITCH,
    KEYWORD_THIS,
    KEYWORD_THROWS,
    KEYWORD_TRY,
    KEYWORD_TYPEDEF,
    KEYWORD_WHILE,

    OPERATOR_EQUIVALENCE,               // ==
    OPERATOR_NOT_EQUIVALENCE,           // !=
    OPERATOR_GREATER_THAN_OR_EQUAL_TO,  // >=
    OPERATOR_LESS_THAN_OR_EQUAL_TO,     // <=
    OPERATOR_INCREMENT,                 // ++
    OPERATOR_DECREMENT,                 // --
    OPERATOR_ADDITION_ASSIGNMENT,       // +=
    OPERATOR_SUBTRACTION_ASSIGNMENT,    // -=
    OPERATOR_MULTIPLICATION_ASSIGNMENT, // *=
    OPERATOR_DIVISION_ASSIGNMENT,       // /=
    OPERATOR_MODULUS_ASSIGNMENT,        // %=
    OPERATOR_BITWISE_AND_ASSIGNMENT,    // &=
    OPERATOR_BITWISE_OR_ASSIGNMENT,     // |=
    OPERATOR_BITWISE_XOR_ASSIGNMENT,    // ^=
    OPERATOR_LEFT_SHIFT,                // <<
    OPERATOR_RIGHT_SHIFT,               // >>
    OPERATOR_RIGHT_SHIFT_UNSIGNED,      // >>>
    OPERATOR_NOT,                       // !
    OPERATOR_BITWISE_AND,               // &
    OPERATOR_BITWISE_OR,                // |
    OPERATOR_BITWISE_XOR,               // ^
    OPERATOR_BITWISE_NOT,               // ~
    OPERATOR_LOGICAL_AND,               // &&
    OPERATOR_LOGICAL_OR,                // ||
} Symbol;

Symbol get_symbol_from_char(char ch);
Symbol get_keyword_from_str(char* str);
char* get_string_from_symbol(Symbol symbol);
bool is_number_symbol(char* str);

#endif